export const VEHICLES_FETCH_DATA_ERROR = 'vehicles/VEHICLES_FETCH_DATA_ERROR';
export const VEHICLES_LOADING = 'vehicles/VEHICLES_LOADING';
export const VEHICLES_FETCH_DATA_SUCCESS = 'vehicles/VEHICLES_FETCH_DATA_SUCCESS';
